"""Add date and time to appointments

Revision ID: b5ae30224e7b
Revises: 63e83e9fcb5c
Create Date: 2025-07-05 12:42:15.310727

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b5ae30224e7b'
down_revision = '63e83e9fcb5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('time', sa.String(), nullable=False))
        batch_op.drop_column('appointment_date')
        batch_op.drop_column('patient_name')

    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_constraint('patients_email_key', type_='unique')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('patients_email_key', ['email'])

    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('appointment_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('time')
        batch_op.drop_column('date')

    # ### end Alembic commands ###
